name: deploy to lambda
on:
  push:
    branches:
      - master
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: package
        run: |
          npm install && zip -r deployment.zip .
      - name: deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: mrGiffer
          zip_file: deployment.zip
